---
- name: Add cisco login banner
  hosts: cisco
  collections:
    - cisco.ios

  tasks:
  - name: Configure the login banner
    cisco.ios.ios_banner:
      banner: login
      text: "{{ net_banner }}"
      state: present